project_id: '479711'
api_token_env: 'CROWDIN_PERSONAL_TOKEN'
preserve_hierarchy: true
files: [
    # JSON translation files
    {
      source: '/src/locales/en/data.json',
      translation: '/src/locales/%two_letters_code%/data.json',
    },
  ]
